//! Code generation for the `.apss/build/` crate.
//!
//! Generates a minimal Rust crate that statically links only the declared
//! standards, producing a project-local composed binary.

use aps_core::lockfile::Lockfile;
use aps_core::resolution::ResolvedProjectConfig;
use std::io::Write;
use std::path::Path;
use thiserror::Error;

/// Errors from code generation.
#[derive(Debug, Error)]
pub enum CodegenError {
    /// Failed to write a generated file.
    #[error("failed to write {path}: {source}")]
    Io {
        path: String,
        source: std::io::Error,
    },
}

/// Generate the `.apss/build/` crate from a resolved config.
///
/// Creates:
/// - `.apss/build/Cargo.toml` with dependencies for each declared standard
/// - `.apss/build/src/main.rs` with register() calls and CLI dispatch
pub fn generate_build_crate(
    config: &ResolvedProjectConfig,
    lockfile: Option<&Lockfile>,
    output_dir: &Path,
) -> Result<Vec<String>, CodegenError> {
    let mut generated_files = Vec::new();

    // Create directories
    let src_dir = output_dir.join("src");
    std::fs::create_dir_all(&src_dir).map_err(|e| CodegenError::Io {
        path: src_dir.display().to_string(),
        source: e,
    })?;

    // Generate Cargo.toml
    let cargo_path = output_dir.join("Cargo.toml");
    generate_cargo_toml(config, lockfile, &cargo_path)?;
    generated_files.push(cargo_path.display().to_string());

    // Generate main.rs
    let main_path = src_dir.join("main.rs");
    generate_main_rs(config, &main_path)?;
    generated_files.push(main_path.display().to_string());

    Ok(generated_files)
}

fn generate_cargo_toml(
    config: &ResolvedProjectConfig,
    lockfile: Option<&Lockfile>,
    path: &Path,
) -> Result<(), CodegenError> {
    let mut content = String::new();

    content.push_str("# AUTO-GENERATED by `apss install`. Do not edit manually.\n\n");
    content.push_str("[package]\n");
    content.push_str("name = \"apss-local\"\n");
    content.push_str("version = \"0.0.0\"\n");
    content.push_str("edition = \"2024\"\n");
    content.push_str("publish = false\n\n");
    content.push_str("[dependencies]\n");

    // Use pinned core version from lockfile, or fall back to current version
    let core_version = lockfile
        .map(|l| l.core.version.as_str())
        .unwrap_or(env!("CARGO_PKG_VERSION"));
    content.push_str(&format!("aps-core = {{ version = \"{core_version}\" }}\n"));

    for standard in config.standards.values() {
        if !standard.enabled {
            continue;
        }
        // Use pinned version from lockfile if available, else fall back to version_req
        let version = lockfile
            .and_then(|l| l.find_package(&standard.id))
            .map(|p| p.version.as_str())
            .unwrap_or(&standard.version_req);
        content.push_str(&format!(
            "{} = {{ version = \"{version}\" }}\n",
            standard.crate_name
        ));
    }

    let mut file = std::fs::File::create(path).map_err(|e| CodegenError::Io {
        path: path.display().to_string(),
        source: e,
    })?;
    file.write_all(content.as_bytes())
        .map_err(|e| CodegenError::Io {
            path: path.display().to_string(),
            source: e,
        })?;

    Ok(())
}

fn generate_main_rs(config: &ResolvedProjectConfig, path: &Path) -> Result<(), CodegenError> {
    let mut content = String::new();

    content.push_str("// AUTO-GENERATED by `apss install`. Do not edit manually.\n\n");
    content.push_str("use aps_core::config;\n");
    content.push_str("use aps_core::registry::ProjectRunner;\n\n");
    content.push_str("fn main() {\n");
    content.push_str(
        "    let config_path = config::find_project_config(&std::env::current_dir().unwrap())\n",
    );
    content.push_str("        .unwrap_or_else(|| std::path::PathBuf::from(\"apss.toml\"));\n");
    content.push_str("    let mut runner = ProjectRunner::from_config_file(&config_path)\n");
    content.push_str("        .expect(\"failed to load apss.toml\");\n\n");

    for standard in config.standards.values() {
        if !standard.enabled {
            continue;
        }
        // Convert crate name (kebab-case) to Rust identifier (snake_case)
        let ident = standard.crate_name.replace('-', "_");
        content.push_str(&format!("    {ident}::register(&mut runner);\n"));
    }

    content.push_str("\n    let args: Vec<String> = std::env::args().skip(1).collect();\n");
    content.push_str("    std::process::exit(runner.run(&args));\n");
    content.push_str("}\n");

    let mut file = std::fs::File::create(path).map_err(|e| CodegenError::Io {
        path: path.display().to_string(),
        source: e,
    })?;
    file.write_all(content.as_bytes())
        .map_err(|e| CodegenError::Io {
            path: path.display().to_string(),
            source: e,
        })?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use aps_core::config::{ProjectInfo, ToolConfig};
    use aps_core::resolution::ResolvedStandard;
    use std::collections::BTreeMap;

    fn test_config() -> ResolvedProjectConfig {
        ResolvedProjectConfig {
            project: ProjectInfo {
                name: "test-project".to_string(),
                apss_version: "v1".to_string(),
            },
            standards: BTreeMap::from([
                (
                    "topology".to_string(),
                    ResolvedStandard {
                        id: "APS-V1-0001".to_string(),
                        slug: "topology".to_string(),
                        version_req: ">=1.0.0".to_string(),
                        enabled: true,
                        substandards: None,
                        config: toml::Value::Table(Default::default()),
                        crate_name: "apss-v1-0001-code-topology".to_string(),
                    },
                ),
                (
                    "fitness".to_string(),
                    ResolvedStandard {
                        id: "APS-V1-0003".to_string(),
                        slug: "fitness".to_string(),
                        version_req: ">=1.0.0".to_string(),
                        enabled: true,
                        substandards: None,
                        config: toml::Value::Table(Default::default()),
                        crate_name: "apss-v1-0003-fitness-functions".to_string(),
                    },
                ),
            ]),
            tool: ToolConfig::default(),
            source_files: vec![],
        }
    }

    #[test]
    fn test_generate_build_crate() {
        let temp = tempfile::tempdir().unwrap();
        let config = test_config();

        let files = generate_build_crate(&config, None, temp.path()).unwrap();
        assert_eq!(files.len(), 2);

        // Verify Cargo.toml
        let cargo = std::fs::read_to_string(temp.path().join("Cargo.toml")).unwrap();
        assert!(cargo.contains("apss-v1-0001-code-topology"));
        assert!(cargo.contains("apss-v1-0003-fitness-functions"));
        assert!(cargo.contains("aps-core"));
        assert!(cargo.contains("publish = false"));

        // Verify main.rs
        let main = std::fs::read_to_string(temp.path().join("src/main.rs")).unwrap();
        assert!(main.contains("apss_v1_0001_code_topology::register"));
        assert!(main.contains("apss_v1_0003_fitness_functions::register"));
        assert!(main.contains("config::find_project_config"));
        assert!(main.contains("ProjectRunner::from_config_file"));
    }

    #[test]
    fn test_generate_skips_disabled() {
        let temp = tempfile::tempdir().unwrap();
        let mut config = test_config();
        config.standards.get_mut("fitness").unwrap().enabled = false;

        generate_build_crate(&config, None, temp.path()).unwrap();

        let cargo = std::fs::read_to_string(temp.path().join("Cargo.toml")).unwrap();
        assert!(cargo.contains("apss-v1-0001-code-topology"));
        assert!(!cargo.contains("apss-v1-0003-fitness-functions"));

        let main = std::fs::read_to_string(temp.path().join("src/main.rs")).unwrap();
        assert!(main.contains("apss_v1_0001_code_topology::register"));
        assert!(!main.contains("apss_v1_0003_fitness_functions::register"));
    }
}
